# Generated by Django 5.0.4 on 2024-04-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.CharField(choices=[('success', 'success'), ('cancel', 'cancel')], editable=False, max_length=10),
        ),
    ]
